In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('per.csv')
data.head()

NewsID                                              Title  \
0  843656  \r\nوزير علوم درجمع استادان نمونه: سن بازنشستگ...   
1  837144  \r\nگردهمايي دانش‌آموختگان موسسه آموزش عالي سو...   
2  436862  \r\nنتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌ن...   
3  227781  \r\nهمايش يكروزه آسيب شناسي مفهوم روابط عمومي ...   
4  174187  \r\nوضعيت اقتصادي و ميزان تحصيلات والدين از مه...   

                                                Body           Date  \
0  \r\nوزير علوم در جمع استادان نمونه كشور گفت: ا...  \r\n138/5//09   
1  \r\nبه گزارش سرويس صنفي آموزشي خبرگزاري دانشجو...  \r\n138/5//09   
2  \r\nنتايج آزمون دوره‌هاي فراگير مقاطع كارشناسي...  \r\n138/3//07   
3                                               \r\n  \r\n138/2//02   
4  \r\nمحمدتقي علوي يزدي، مجري اين طرح پژوهشي در ...  \r\n138/1//08   

          Time              Category    Category2  
0  \r\n0:9::18           \r\nآموزشي-   \r\nآموزشي  
1  \r\n1:4::11           \r\nآموزشي-   \r\nآموزشي  
2  \r\n1:0::03           \r\nآموزشي-   \r\nآموزشي  
3  \r\n1:3::42  \r\nاجتماعي-خانواده-  \r\nاجتماعي  
4  \r\n1:1::49           \r\nآموزشي-   \r\nآموزشي

In [3]:
with open('stopwords.txt', encoding='utf-8') as stopwords_file:
    stopwords = stopwords_file.readlines()
stopwords = [line.replace('\n', '') for line in stopwords]
stopwords

['!',
 '"',
 '#',
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '/',
 ':',
 '[',
 ']',
 '«',
 '»',
 '،',
 '؛',
 '؟',
 'آباد',
 'آخ',
 'آخر',
 'آخرها',
 'آخه',
 'آدمهاست',
 'آرام',
 'آرام آرام',
 'آره',
 'آری',
 'آزادانه',
 'آسان',
 'آسیب پذیرند',
 'آشنایند',
 'آشکارا',
 'آقا',
 'آقای',
 'آقایان',
 'آمد',
 'آمدن',
 'آمده',
 'آمرانه',
 'آن',
 'آن گاه',
 'آنان',
 'آنانی',
 'آنجا',
 'آنرا',
 'آنطور',
 'آنقدر',
 'آنها',
 'آنهاست',
 'آنچنان',
 'آنچنان که',
 'آنچه',
 'آنکه',
 'آنگاه',
 'آن\u200cها',
 'آهان',
 'آهای',
 'آور',
 'آورد',
 'آوردن',
 'آورده',
 'آوه',
 'آی',
 'آیا',
 'آید',
 'آیند',
 'ا',
 'اتفاقا',
 'اثرِ',
 'اجراست',
 'احتراما',
 'احتمالا',
 'احیاناً',
 'اخیر',
 'اخیراً',
 'اری',
 'از',
 'از آن پس',
 'از جمله',
 'ازاین رو',
 'ازجمله',
 'ازش',
 'اساسا',
 'اساساً',
 'است',
 'استفاد',
 'استفاده',
 'اسلامی اند',
 'اش',
 'اشتباها',
 'اشکارا',
 'اصلا',
 'اصلاً',
 'اصولا',
 'اصولاً',
 'اعلام',
 'اغلب',
 'افزود',
 'افسوس',
 'اقل',
 'اقلیت',
 'الا',
 'الان',
 'البته',
 'البتّه',
 'الهی',
 'الی',
 '

In [4]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Hacker\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Hacker\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [5]:
nltk_stopwords = nltk.corpus.stopwords.words('english')
stopwords.extend(nltk_stopwords)
len(stopwords)

1495

In [6]:
import hazm
stemmer = hazm.Stemmer()

In [7]:
stemmer.stem('کتاب‌ها')

'کتاب'

In [8]:
from hazm import word_tokenize

In [9]:
dataset = pd.DataFrame(columns=['title_body', 'category'])
for index, row in data.iterrows():
    title_body = row['Title'] + ' ' + row['Body']
    title_body_tokenized = word_tokenize(title_body)
    title_body_tokenized_filtered = [w for w in title_body_tokenized if not w in stopwords]
    title_body_tokenized_filtered_stemmed = [stemmer.stem(w) for w in title_body_tokenized_filtered]
    dataset.loc[index]= {
        'title_body': ' '.join(title_body_tokenized_filtered_stemmed).replace('\r', ''),
        'category': row['Category2'].replace('\n', '').replace('\r', '')
    }

In [10]:
dataset.head()

title_body category
0   وزير علو درجمع استاد نمونه سن بازنشستگي استاد...   آموزشي
1   گردهمايي دانش‌آموختگ موسسه آموز عالي سوره برگ...   آموزشي
2   نتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور ...   آموزشي
3   هماي يكروزه آسيب شناسي مفهو روابط عمومي بابلس...  اجتماعي
4   وضعي اقتصادي ميز تحصيل والدين مهمترين عوامل م...   آموزشي

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
vectorizer = TfidfVectorizer()
vectorizer.fit(dataset['title_body'])

TfidfVectorizer()

In [13]:
X = vectorizer.transform(dataset['title_body'])

In [14]:
X

<10999x60817 sparse matrix of type '<class 'numpy.float64'>'
	with 1785163 stored elements in Compressed Sparse Row format>

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le = LabelEncoder()
y = le.fit_transform(dataset['category'])

In [17]:
le.classes_

array(['آموزشي', 'اجتماعي', 'اقتصادي', 'بهداشتي', 'تاريخي', 'سياسي',
       'علمي', 'فرهنگي', 'فقه و حقوق', 'مذهبي', 'ورزشي'], dtype=object)

In [18]:
len(y)

10999

In [19]:
import numpy as np
print(np.unique(dataset['category']))

['آموزشي' 'اجتماعي' 'اقتصادي' 'بهداشتي' 'تاريخي' 'سياسي' 'علمي' 'فرهنگي'
 'فقه و حقوق' 'مذهبي' 'ورزشي']


In [20]:
np.shape(X)

(10999, 60817)

In [21]:
np.shape(y)

(10999,)

In [22]:
from sklearn.ensemble import IsolationForest

In [23]:
IF = IsolationForest(contamination=0.05)
X_outlier = IF.fit_predict(X)

In [24]:
np.unique(X_outlier, return_counts=True)

(array([-1,  1]), array([  550, 10449], dtype=int64))

In [36]:
X_outlier == 1

array([ True,  True,  True, ...,  True,  True,  True])

In [25]:
X = X[X_outlier == 1]

In [26]:
y = y[X_outlier == 1]

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [29]:
y_train

array([ 3,  4,  8, ...,  1,  8, 10])

In [30]:
from sklearn import svm

In [31]:
svmc = svm.SVC()
svmc.fit(X_train, y_train)

SVC()

In [32]:
svmc.score(X_test, y_test)

0.8335246842709529

In [33]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = svmc.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.92      0.85       218
           1       0.59      0.68      0.63       227
           2       0.80      0.77      0.79       258
           3       0.88      0.93      0.90       250
           4       0.84      0.83      0.83       157
           5       0.76      0.73      0.74       255
           6       0.87      0.76      0.81       247
           7       0.87      0.87      0.87       253
           8       0.89      0.84      0.86       247
           9       0.96      0.91      0.93       248
          10       0.96      0.93      0.95       253

    accuracy                           0.83      2613
   macro avg       0.84      0.83      0.83      2613
weighted avg       0.84      0.83      0.83      2613



In [34]:
print(confusion_matrix(y_test, y_pred))

[[201   6   2   1   0   2   5   1   0   0   0]
 [ 16 154  17   6   7   8   4   8   1   2   4]
 [  1  35 199   2   1   9   4   3   3   1   0]
 [  1   9   0 233   0   2   4   0   0   0   1]
 [  3   4   0   0 130  11   0   6   2   1   0]
 [  7  13  13   0  10 186   3   4  16   3   0]
 [ 18   8   4  20   0   4 187   3   0   0   3]
 [  4   9   4   0   2   4   5 221   2   2   0]
 [  3   8   4   1   5  10   3   4 207   1   1]
 [  1  10   3   0   0   6   0   2   1 225   0]
 [  0   7   2   2   0   4   1   1   1   0 235]]
